/** Same choices as legacy `xp_settings.js` for `/mod xp settings`. */
module.exports = [
  { name: 'Monday, Tuesday', value: 'mon,tue' },
  { name: 'Monday, Tuesday, Wednesday', value: 'mon,tue,wed' },
  { name: 'Monday, Tuesday, Wednesday, Thursday', value: 'mon,tue,wed,thu' },
  { name: 'Monday, Tuesday, Wednesday, Thursday, Friday', value: 'mon,tue,wed,thu,fri' },
  { name: 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday', value: 'mon,tue,wed,thu,fri,sat' },
  {
    name: 'Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday',
    value: 'mon,tue,wed,thu,fri,sat,sun',
  },
  { name: 'Tuesday, Wednesday', value: 'tue,wed' },
  { name: 'Tuesday, Wednesday, Thursday', value: 'tue,wed,thu' },
  { name: 'Tuesday, Wednesday, Thursday, Friday', value: 'tue,wed,thu,fri' },
  { name: 'Tuesday, Wednesday, Thursday, Friday, Saturday', value: 'tue,wed,thu,fri,sat' },
  { name: 'Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday', value: 'tue,wed,thu,fri,sat,sun' },
  { name: 'Wednesday, Thursday', value: 'wed,thu' },
  { name: 'Wednesday, Thursday, Friday', value: 'wed,thu,fri' },
  { name: 'Wednesday, Thursday, Friday, Saturday', value: 'wed,thu,fri,sat' },
  { name: 'Wednesday, Thursday, Friday, Saturday, Sunday', value: 'wed,thu,fri,sat,sun' },
  { name: 'Thursday, Friday', value: 'thu,fri' },
  { name: 'Thursday, Friday, Saturday', value: 'thu,fri,sat' },
  { name: 'Thursday, Friday, Saturday, Sunday', value: 'thu,fri,sat,sun' },
  { name: 'Friday, Saturday', value: 'fri,sat' },
  { name: 'Friday, Saturday, Sunday', value: 'fri,sat,sun' },
  { name: 'Saturday', value: 'sat' },
  { name: 'Saturday, Sunday', value: 'sat,sun' },
  { name: 'Sunday', value: 'sun' },
];
