/** F95 meme filenames served from https://overlord.lordainz.xyz/f/f95/ */
const MEME_BASE_URL = 'https://overlord.lordainz.xyz/f/f95/';

const MEME_FILES = [
  "1PunchMan.mp4",
  "2BDance.gif",
  "35861.gif",
  "843968494105526284.gif",
  "919776280411537428.webp",
  "A mistake.jpg",
  "aGXmkjYR_700w_0.jpg",
  "AloneInTheDarkWithNothingButYourThoughts.jpg",
  "AnalProbe.gif",
  "anGrwkW9_700wv_0.mp4",
  "AngrySJW.png",
  "AnimalCruelty.gif",
  "AnimeGurlJrk.jpg",
  "AOCRider.jpg",
  "Aploz.gif",
  "AraAra.jpg",
  "ASS.gif",
  "aVbyBL8_700bwp.webp",
  "aW3JLV5g_700w_0.jpg",
  "BaasBump.gif",
  "Babe.gif",
  "BadAtMath.jpg",
  "BallsPillow.jpg",
  "BAM.gif",
  "BamSlamSlap.gif",
  "Bananakin.png",
  "Because I can.gif",
  "BeNormal.jpg",
  "BFC.jpg",
  "BigBoi.gif",
  "BlackOEJThrow.gif",
  "Blonde.mp4",
  "BobGettinSum.jpg",
  "boobies.gif",
  "BoobWave.gif",
  "BreakyJump.gif",
  "CantSee.gif",
  "CockSucker.mp4",
  "Contemplate.gif",
  "Copium.gif",
  "Crazy.gif",
  "CrazyWhite.gif",
  "Creeper-unscreen.gif",
  "CreepySaricaKiss.png",
  "CuirCuirNoPP.gif",
  "CuirCuirOhDeer.gif",
  "CumOn.gif",
  "Cuntrobics.gif",
  "Daddy.gif",
  "DancingPepe.gif",
  "Danney Deleto.jpg",
  "dedpepe.gif",
  "Degenerete.jpg",
  "Derp Cat.jpg",
  "Derp Cat2.jpg",
  "Despair Pepe.webp",
  "DifferentClothesSameViessa.gif",
  "DildoOfConsequence.jpg",
  "Dr Phil.gif",
  "Dragon Mon.jpg",
  "DuckWakAwei.gif",
  "ElevatorSurprise.gif",
  "Evil Toilet Hands.gif",
  "EvilCat.gif",
  "Explosion.gif",
  "F95Zone Musical.mp4",
  "Facial.gif",
  "FakeCri.gif",
  "Farthionic.gif",
  "FastFood.gif",
  "FBI.jpg",
  "Fire.gif",
  "Fishjob.mp4",
  "For Viessa.gif",
  "GameilTheSemenSampler.gif",
  "geh.gif",
  "Geh.mp4",
  "Gehvant.gif",
  "Generational Weakness.mp4",
  "Genie.jpg",
  "GiveMeSomethingForTheCringe.jpg",
  "GlassySky.gif",
  "GojiraROR.gif",
  "GoodbyeSmolPPs.gif",
  "GreetingsKindSirSepe.gif",
  "HagridMVP.gif",
  "HaHaHa.jpg",
  "hajime no ippo.gif",
  "Happy4U.jpg",
  "He...He.jpg",
  "HeadNod.gif",
  "HeadWindow.gif",
  "Heartss.gif",
  "HeavyPeeer.gif",
  "HeedMuhWarning.gif",
  "Hehe.jpg",
  "Hi.gif",
  "HornyPolice.jpg",
  "HowToGetRespectedUserBadge.gif",
  "Hubris of Trial.gif",
  "Huh.png",
  "HurtsInMuhMeowMeow.jpg",
  "I'll get you for this, Thicc.gif",
  "I'm Back Cunts.gif",
  "IHaveStringsAndImNotFree.gif",
  "im-watching-stalking.gif",
  "immacominrf96.gif",
  "itznikisgeh.jpg",
  "JediPepe.gif",
  "Jeevant.gif",
  "Jesus Sins.jpg",
  "JesusBChrist.gif",
  "JesusSaveMe.mp4",
  "JrFurries.gif",
  "KripiFemili.jpg",
  "LazyJRs.gif",
  "LeaveBritneyAlone.jpg",
  "LeoCard.jpg",
  "LickyDogyLicky.gif",
  "Like Whore.png",
  "LoliGF.gif",
  "Maleficent.gif",
  "MaleficentBird.gif",
  "MhmMhm.gif",
  "Michvlin.jpg",
  "Midget Meme.mp4",
  "MiKillMiself.gif",
  "MilkyCity.gif",
  "Minesheep.mp4",
  "MissedVeggiePP.png",
  "Mistake.webp",
  "MoCkiNg.jpg",
  "Mod App Rejected.gif",
  "ModCompetition.gif",
  "Mods.webp",
  "ModSarica.gif",
  "N7+Slut.gif",
  "NiceFakinPost.gif",
  "No Way.jpg",
  "NoHoeMal.gif",
  "NoMore.jpg",
  "NotANormalBoy.jpg",
  "NotRape.jpg",
  "NTRBob.jpg",
  "OEJ.gif",
  "OEJ&Soul.gif",
  "OEJSon.gif",
  "OEJSureAnalVirgin.gif",
  "OEJSureVirgin.gif",
  "OhRight.webp",
  "Ouch.gif",
  "Partanen.gif",
  "PartanenPunish.gif",
  "partanentheeternalcleaner.gif",
  "peepo-driveby.gif",
  "PepeCiLaf.gif",
  "PepeHartNoHomo.png",
  "PepeHug.webp",
  "PepeJediFast.gif",
  "PepePPFinger.gif",
  "PepePunch.gif",
  "PepeSaricaDead.png",
  "PepeSaricaGrin.png",
  "pepeSaricaSweating.png",
  "PepeSaricaWeird.png",
  "PepeSarPooPoo.png",
  "PepeSpank.gif",
  "PepKek.gif",
  "Pezzo2.mp4",
  "Pezzo3.mp4",
  "PezzoPepsi.gif",
  "PezzosPowerAbuse.gif",
  "PezzoStaffAbusePart2.gif",
  "PezzoTraitor.png",
  "Phatass.mp4",
  "PikaBustUpSuruprise.jpg",
  "Pokemon.jpg",
  "Police.gif",
  "pondering-my-orb-header-art.webp",
  "Poop.mp4",
  "Postin'Cringe.jpg",
  "PPBottle.jpg",
  "PPShower.gif",
  "Problem.gif",
  "Profound Sadness.mp4",
  "Programming.webp",
  "ProofAgainstViessa.jpg",
  "ProofJeevantCocksucker.jpg",
  "RainRainGoAway.gif",
  "Reality.jpg",
  "RedCardGetOut.gif",
  "RejectedSarica.gif",
  "rf96thelolinut.gif",
  "Risitas.png",
  "RWoosh.jpg",
  "RyahnTheWerewolf.gif",
  "SadButFAKU.png",
  "Sadception.jpg",
  "SAHC 2.gif",
  "SAHC.gif",
  "SamSpanksSlut.png",
  "Sarica.gif",
  "SaricaFirstWeek.gif",
  "SaricaGump.gif",
  "SaricaNoModerator.gif",
  "SaricaPepeCross.png",
  "SaricaPepeSip.png",
  "SaricasFutureJob.gif",
  "SaricaWTF.gif",
  "Sarince.gif",
  "SashaGrey.jpg",
  "ScaryTrollFace.gif",
  "SealThonk.png",
  "Sepe Hmm.png",
  "Shaky Boi.jpg",
  "SharkCookie.gif",
  "Shetupid-Hulk.gif",
  "Shok.png",
  "SillyAngryZoner.gif",
  "Sir Wolf.gif",
  "SJSmile.gif",
  "SJSuck.gif",
  "SlappyDogButt.mp4",
  "SleepAwake.gif",
  "Smile.gif",
  "Smurt Meme.gif",
  "SoulPepe.gif",
  "Spageticock.gif",
  "staff.png",
  "StearyBirb.gif",
  "Steven.gif",
  "StillViessa.gif",
  "StorageKillers.gif",
  "StudiesxD.jpg",
  "TakeOutTheTrash.gif",
  "Teapot.webp",
  "TenSmolPPBoys.gif",
  "TH.gif",
  "ThatsRacist.gif",
  "TheCurryGang.gif",
  "TheFascist95Zone.gif",
  "THEHug.webm",
  "THICC.gif",
  "ThumbsUp.gif",
  "TittyMouthfulDog.gif",
  "Togeta4evagif.gif",
  "Tongue Tricks.mp4",
  "TrainHole.gif",
  "TransWoman.jpg",
  "TrollLikeMe.gif",
  "TrutHrts.jpg",
  "TTs.jpg",
  "Uncir.jpg",
  "Unfakbl.gif",
  "Upperlick.gif",
  "veggie pp salad.jpg",
  "VeggieBuddgie.gif",
  "Viessa.gif",
  "Vomit.gif",
  "VomitCat.gif",
  "WaterFall.gif",
  "WhyDontYouHaveASeatRightOverHere.gif",
  "Wind.gif",
  "Wish Upon A Star.webp",
  "Witch.gif",
  "Woke.gif",
  "WokeFace.png",
  "Wolf-unscreen.gif",
  "WTF.jpg",
  "YGeh.mp4",
  "YGeh.png",
  "YHASUFORSAKENMI.jpg",
  "YRUGEH.jpg",
  "YUGEH.gif",
  "Zemax.gif",
  "Zeo.gif"
];

const VIDEO_EXTENSIONS = new Set(['.mp4', '.webm']);

function memeUrl(filename) {
  return `${MEME_BASE_URL}${encodeURIComponent(filename)}`;
}

function pickRandomMeme() {
  const index = Math.floor(Math.random() * MEME_FILES.length);
  return MEME_FILES[index];
}

function isVideoMeme(filename) {
  const dot = filename.lastIndexOf('.');
  if (dot === -1) return false;
  return VIDEO_EXTENSIONS.has(filename.slice(dot).toLowerCase());
}

module.exports = {
  MEME_BASE_URL,
  MEME_FILES,
  memeUrl,
  pickRandomMeme,
  isVideoMeme,
};
